### PR TITLE
S3 proj_trans() Generic

### LINKED ISSUE #49: replace proj_trans with wk::xy impl.

### PR DESCRIPTION
**Pull request by anthonynorth**
Re-implements proj_trans(), leveraging `wk::wk_handle()` and `proj_trans_create()`. This allows for inputs to take any form that `wk::wk_handle()` supports, including:
- Coordinate matrices
- Data frames with coordinates
- {wk} geometry vectors: xy, wkt, wkb, rct, 
- {sf} geometry vectors
- {geos} geometry vectors
- {geoarrow} geometry vectors
- {s2} geography vectors (although this makes little sense)
- A data frame containing a geometry/geography vector from wk, sf, geos, geoarrow, s2

For coordinate matrices / data frames, there's an approximate 15-20% compute overhead compared with previous implementation. Benchmark:

``` r
library(PROJ)

xy <- wk::xy(
  runif(1e6, -180, 180),
  runif(1e6, -90, 90),
  "OGC:CRS84"
)

coords <- as.matrix(xy)
sfc <- sf::st_as_sfc(xy)

bench::mark(
  .Call(PROJ:::C_proj_trans_xy, wk::xy_x(xy), wk::xy_y(xy), "OGC:CRS84", "EPSG:3857"),
  .Call(PROJ:::C_proj_trans_list, unclass(xy), "OGC:CRS84", "EPSG:3857"),
  proj_trans(xy, "EPSG:3857"),
  sf::sf_project("OGC:CRS84", "EPSG:3857", coords),
  proj_trans(sfc, "EPSG:3857"),
  sf::st_transform(sfc, "EPSG:3857"),
  iterations = 5,
  check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 6 × 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 ".Call(PROJ:::C_proj_trans_xy,… 167.98ms 168.92ms     5.92     15.3MB    0
#> 2 ".Call(PROJ:::C_proj_trans_lis…  163.6ms 164.08ms     6.04     15.3MB    1.21
#> 3 "proj_trans(xy, \"EPSG:3857\")" 213.58ms 213.74ms     4.64     15.4MB    0.929
#> 4 "sf::sf_project(\"OGC:CRS84\",… 164.49ms 168.31ms     5.95     15.3MB    1.19
#> 5 "proj_trans(sfc, \"EPSG:3857\"… 598.56ms 652.47ms     1.31     30.8MB    1.31
#> 6 "sf::st_transform(sfc, \"EPSG:…    3.03s    3.38s     0.293   114.8MB    0.820
```

<sup>Created on 2024-03-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Closes #49 

## Breaking changes

- Z and T coordinate vectors are always supplied in the `x` parameter
- Renamed parameters: `target -> target_crs`, `source -> source_crs`
- `source_crs` defaults to the input `crs` if available, falling back to `OGC:CRS84`
- If coordinate matrices are named, expects names "x", "y" and optionally "z" and/or "m" columns. Previously names were ignored
- Coordinate data frames expect names "x", "y" and optionally "z" and/or "m" columns
- Output coordinate matrix or data frame will always contain names "x", "y" and optionally "z" and/or "m" depending on `use_z` and `use_m` parameters

### CODE REVIEW

**Comment by anthonynorth** [comment]
[Failing tests](https://github.com/hypertidy/PROJ/actions/runs/8387710654/job/22970433192?pr=56#step:8:204) are related to paleolimbot/wk#217 which hasn't yet landed on CRAN.

**Comment by anthonynorth** [comment]
I haven't yet removed the existing `C_proj_trans_xy()` and `C_proj_trans_list()` functions. Useful for a benchmark, but wasn't sure what you want to do with them. We can refactor these to avoid taking any perf hit for the matrix/dataframe usage if it's important.

I haven't attempted to replicate this behaviour in the {wk} transformer. I think it's doable though
https://github.com/hypertidy/PROJ/blob/7f4c4e7b390d3063c17dcc5a475aa68683216cda/src/C_proj_trans.c#L78-L81

**Review by mdsumner — APPROVED** [review]
lgtm!

**Comment by mdsumner** [comment]
any reason not to merge this in?    I'm keen to do that and move on, I can spend some time here now

**Comment by anthonynorth** [comment]
Sorry for the delay, I've been unable to get back to this. I'll drop the superseded c functions and then we can merge.

We could put in a guard for the failing tests also since they're dependent on wk > 0.9.1 which isn't on cran.

**Pull request merged**
