### PR TITLE
Use non-default context

### PR DESCRIPTION
**Pull request by anthonynorth**
{wk} transformers use non-default context to isolate {PROJ} from other packages.

### CODE REVIEW

**Comment by anthonynorth** [comment]
@mdsumner, I think this change is leak free, but I'm not certain. The output below suggests maybe a problem, but forcibly running `gc()` after reduces `possibly lost` to 0 :shrug:

## Valgrind
```bash
R -d "valgrind" -e "devtools::test()"
```

### Output
```
==36367== 
==36367== HEAP SUMMARY:
==36367==     in use at exit: 119,545,088 bytes in 52,147 blocks
==36367==   total heap usage: 1,356,036 allocs, 1,303,889 frees, 626,206,877 bytes allocated
==36367== 
==36367== LEAK SUMMARY:
==36367==    definitely lost: 0 bytes in 0 blocks
==36367==    indirectly lost: 0 bytes in 0 blocks
==36367==      possibly lost: 2,013,648 bytes in 461 blocks
==36367==    still reachable: 117,531,440 bytes in 51,686 blocks
==36367==                       of which reachable via heuristic:
==36367==                         length64           : 2,637,440 bytes in 24,559 blocks
==36367==                         newarray           : 4,264 bytes in 1 blocks
==36367==         suppressed: 0 bytes in 0 blocks
==36367== Rerun with --leak-check=full to see details of leaked memory
==36367== 
==36367== For lists of detected and suppressed errors, rerun with: -s
==36367== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by mdsumner** [comment]
I don't know about valgrind, looks ok?   I don't think I have it in me to set up and run with valgrind atm

**Comment by anthonynorth** [comment]
Ok I think we can ignore this one.

I would have expected garbage collection to occur before R terminates. Running `gc()` afterwards:

```
# R -d "valgrind" -e "devtools::test(); gc()"`

==50088== 
==50088== HEAP SUMMARY:
==50088==     in use at exit: 113,046,870 bytes in 24,938 blocks
==50088==   total heap usage: 1,336,051 allocs, 1,311,113 frees, 610,469,140 bytes allocated
==50088== 
==50088== LEAK SUMMARY:
==50088==    definitely lost: 0 bytes in 0 blocks
==50088==    indirectly lost: 0 bytes in 0 blocks
==50088==      possibly lost: 0 bytes in 0 blocks
==50088==    still reachable: 113,046,870 bytes in 24,938 blocks
==50088==                       of which reachable via heuristic:
==50088==                         newarray           : 4,264 bytes in 1 blocks
==50088==         suppressed: 0 bytes in 0 blocks
==50088== Rerun with --leak-check=full to see details of leaked memory
==50088== 
==50088== For lists of detected and suppressed errors, rerun with: -s
==50088== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by mdsumner** [comment]
have you seen rhub2!! omg

https://github.com/hypertidy/PROJ/actions/runs/7590300953

**Comment by anthonynorth** [comment]
I have not. I see valgrind passes, so that's good. I haven't looked into the failures; are they related to this PR? If not I think we merge and fix those issues up later?

**Comment by mdsumner** [comment]
I don't think they're related, merge away

**Pull request merged**
